services:
  app-service:
    image: kejji/lgr-app-service
    restart: "unless-stopped"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: kejji/lgr-auth-service
    restart: "unless-stopped"
    ports:
      - "3000:3000"
